version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: simu-net-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: simu_net
    volumes:
      - mongodb_data:/data/db
    networks:
      - simu-net

  redis:
    image: redis:7.2-alpine
    container_name: simu-net-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - simu-net

  api:
    build: .
    container_name: simu-net-api
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"  # Prometheus metrics
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./data:/app/data
    networks:
      - simu-net

  prometheus:
    image: prom/prometheus:latest
    container_name: simu-net-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - simu-net

  grafana:
    image: grafana/grafana:latest
    container_name: simu-net-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - simu-net

volumes:
  mongodb_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  simu-net:
    driver: bridge